name: Process HN Jobs

on:
  # Schedule updates (00:30 && 12:30 UTC daily)
  schedule: [{ cron: '0 * * * *' }]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: { branches: ['master'] }

env:
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  SUPABASE_KEY: ${{ vars.SUPABASE_KEY }}

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: pnpm
      - run: pnpm install
      - run: pnpm turbo lint prettier
      - name: Run Who Is Hiring script
        run: node apps/registry/scripts/jobs/getLatestWhoIsHiring.js
      - name: Output first 10 lines of generated JSON
        run: head -n 10 apps/registry/scripts/jobs/output/whoIsHiring.json
      - name: Upload Who Is Hiring data as artifact
        uses: actions/upload-artifact@v2
        with:
          name: who-is-hiring-data
          path: apps/registry/scripts/jobs/output/whoIsHiring.json
          retention-days: 7
